variable "internal_cidr" {}
variable "internal_gw" {}
variable "director_internal_ip" {}
variable "jumpbox_internal_ip" {}
variable "external_ip" {}
variable "auth_url" {}
variable "az" {}
variable "default_key_name" {}
variable "default_security_group" {}
variable "net_id" {}
variable "openstack_project" {}
variable "openstack_domain" {}
variable "region" {}
variable "env_id" {}
variable "private_key" {}
variable "external_network" {}
variable "external_network_uuid" {}
variable "dns" {}
